openapi: 3.0.3
info:
  title: Snyk AccessRequests OpenSourceSettings API
  version: REST
servers:
- description: Snyk REST API
  url: https://api.snyk.io/rest
security:
- APIToken: []
- BearerAuth: []
tags:
- name: OpenSourceSettings
paths:
  /orgs/{org_id}/settings/opensource:
    get:
      description: 'Returns settings for your Org which may also be controlled at the Group level.


        #### Required permissions


        - `View Organization (org.read)`'
      operationId: getOpenSourceSettingsForOrg
      parameters:
      - $ref: '#/components/parameters/Version'
      - description: The id of the org.
        in: path
        name: org_id
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '200':
          content:
            application/vnd.api+json:
              schema:
                additionalProperties: false
                properties:
                  data:
                    description: The Open Source settings for an Org.
                    properties:
                      attributes:
                        properties:
                          reachability:
                            description: The reachability setting for Org.
                            properties:
                              enabled:
                                description: When enabled projects in this Org will be scanned for reachable vulnerabilities.
                                example: true
                                type: boolean
                            type: object
                        type: object
                      id:
                        description: ID
                        example: ea536a06-0566-40ca-b96b-155568aa2027
                        format: uuid
                        type: string
                      type:
                        description: Content type
                        example: opensource_settings
                        type: string
                    type: object
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    $ref: '#/components/schemas/Links'
                required:
                - jsonapi
                - data
                - links
                type: object
          description: The Open Source Settings for given Org.
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: Get the Open Source Settings for an Org. (Early Access)
      tags:
      - OpenSourceSettings
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - 2024-10-15~beta
      x-snyk-api-resource: open_source
      x-snyk-api-stability: beta
      x-snyk-api-version: 2024-10-15~beta
      x-stability-level: beta
  /groups/{group_id}/settings/opensource/broker:
    delete:
      description: 'Deletes the opensource broker setting for the group by uninstalling the Snyk App


        #### Required permissions


        - `Install Apps (group.app.install)`'
      operationId: deleteOpensourceBrokerSettingForGroup
      parameters:
      - $ref: '#/components/parameters/Version'
      - description: Group ID
        in: path
        name: group_id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Successfully deleted opensource broker setting
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: Delete opensource broker setting for group
      tags:
      - OpenSourceSettings
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - '2024-10-15'
      x-snyk-api-resource: opensourceSettings
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-10-15'
      x-stability-level: stable
    get:
      description: 'Returns whether the opensource broker setting is enabled for the group


        #### Required permissions


        - `View Groups (group.read)`'
      operationId: getOpensourceBrokerSettingForGroup
      parameters:
      - $ref: '#/components/parameters/Version'
      - description: Group ID
        in: path
        name: group_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/vnd.api+json:
              schema:
                properties:
                  data:
                    additionalProperties: false
                    description: opensource broker setting
                    properties:
                      enabled:
                        description: Whether the opensource broker setting is enabled
                        example: true
                        type: boolean
                    required:
                    - enabled
                    type: object
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    $ref: '#/components/schemas/SelfLink'
          description: Successfully retrieved opensource broker setting
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: Get opensource broker setting for group
      tags:
      - OpenSourceSettings
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - '2024-10-15'
      x-snyk-api-resource: opensourceSettings
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-10-15'
      x-stability-level: stable
    post:
      description: 'Enables the opensource broker setting for a group by installing the Snyk App


        #### Required permissions


        - `Install Apps (group.app.install)`'
      operationId: enableOpensourceBrokerForGroup
      parameters:
      - $ref: '#/components/parameters/Version'
      - description: Group ID
        in: path
        name: group_id
        required: true
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/EmptyRequestBody'
      responses:
        '201':
          content:
            application/vnd.api+json:
              schema:
                properties:
                  data:
                    additionalProperties: false
                    description: enable result
                    properties:
                      status:
                        enum:
                        - success
                        example: success
                        type: string
                    type: object
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    additionalProperties: false
                    type: object
          description: Enabled opensource broker successfully
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            location:
              $ref: '#/components/headers/LocationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: Enable opensource broker for group
      tags:
      - OpenSourceSettings
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - '2024-10-15'
      x-snyk-api-resource: opensourceSettings
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-10-15'
      x-stability-level: stable
  /orgs/{org_id}/settings/opensource/broker:
    delete:
      description: 'Deletes the opensource broker setting for the organization by uninstalling the Snyk App


        #### Required permissions


        - `Install Apps (org.app.install)`'
      operationId: deleteOpensourceBrokerSettingForOrg
      parameters:
      - $ref: '#/components/parameters/Version'
      - description: Org ID
        in: path
        name: org_id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Successfully deleted opensource broker setting
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: Delete opensource broker setting for organization
      tags:
      - OpenSourceSettings
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - '2024-10-15'
      x-snyk-api-resource: opensourceSettings
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-10-15'
      x-stability-level: stable
    get:
      description: 'Returns whether the opensource broker setting is enabled for the organization


        #### Required permissions


        - `View Organization (org.read)`'
      operationId: getOpensourceBrokerSetting
      parameters:
      - $ref: '#/components/parameters/Version'
      - description: Org ID
        in: path
        name: org_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/vnd.api+json:
              schema:
                properties:
                  data:
                    additionalProperties: false
                    description: opensource broker setting
                    properties:
                      enabled:
                        description: Whether the opensource broker setting is enabled
                        example: true
                        type: boolean
                    required:
                    - enabled
                    type: object
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    $ref: '#/components/schemas/SelfLink'
          description: Successfully retrieved opensource broker setting
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: Get opensource broker setting for organization
      tags:
      - OpenSourceSettings
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - '2024-10-15'
      x-snyk-api-resource: opensourceSettings
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-10-15'
      x-stability-level: stable
    post:
      description: 'Enables the opensource broker setting for an organization by installing the Snyk App


        #### Required permissions


        - `Install Apps (org.app.install)`'
      operationId: enableOpensourceBrokerForOrg
      parameters:
      - $ref: '#/components/parameters/Version'
      - description: Org ID
        in: path
        name: org_id
        required: true
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/EmptyRequestBody'
      responses:
        '201':
          content:
            application/vnd.api+json:
              schema:
                properties:
                  data:
                    additionalProperties: false
                    description: enable result
                    properties:
                      status:
                        enum:
                        - success
                        example: success
                        type: string
                    type: object
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    additionalProperties: false
                    type: object
          description: Enabled opensource broker successfully
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            location:
              $ref: '#/components/headers/LocationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: Enable opensource broker for organization
      tags:
      - OpenSourceSettings
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - '2024-10-15'
      x-snyk-api-resource: opensourceSettings
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-10-15'
      x-stability-level: stable
  /orgs/{org_id}/settings/opensource/{ecosystem}/broker:
    get:
      description: 'Retrieves all Broker settings of a specific Open Source Ecosystem for an Organization


        #### Required permissions


        - `View Organization (org.read)`'
      operationId: getOpensourceBrokerEcosystemSettingsForOrg
      parameters:
      - $ref: '#/components/parameters/Version'
      - description: Org ID
        in: path
        name: org_id
        required: true
        schema:
          type: string
      - description: The ecosystem identifier
        in: path
        name: ecosystem
        required: true
        schema:
          enum:
          - Dotnet
          - Golang
          type: string
      responses:
        '200':
          content:
            application/vnd.api+json:
              examples:
                Empty:
                  $ref: '#/components/examples/GetBrokerSettingsResponseEmpty'
                WithIntegrations:
                  $ref: '#/components/examples/GetBrokerSettingsResponseWithIntegrations'
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/BrokerSettings'
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    $ref: '#/components/schemas/PaginatedLinks'
          description: Successfully retrieved Broker settings
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: Get opensource broker settings of ecosystem for organization
      tags:
      - OpenSourceSettings
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - '2024-10-15'
      x-snyk-api-resource: opensourceSettings
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-10-15'
      x-stability-level: stable
    patch:
      description: 'Updates all Broker settings of a specific Open Source Ecosystem for an Organization.

        This endpoint has JSON-PATCH semantics: only provided Broker integrations are updated.

        Provide an empty value for `urls` to remove a Broker integration.


        #### Required permissions


        - `Edit Organization (org.edit)`'
      operationId: updateOpensourceBrokerEcosystemSettingsForOrg
      parameters:
      - $ref: '#/components/parameters/Version'
      - description: Org ID
        in: path
        name: org_id
        required: true
        schema:
          type: string
      - description: The ecosystem identifier
        in: path
        name: ecosystem
        required: true
        schema:
          enum:
          - Dotnet
          - Golang
          type: string
      requestBody:
        content:
          application/vnd.api+json:
            examples:
              AddIntegration:
                $ref: '#/components/examples/PostBrokerSettingsRequestAddIntegration'
              EditIntegrations:
                $ref: '#/components/examples/PostBrokerSettingsRequestEditIntegrations'
              RemoveIntegration:
                $ref: '#/components/examples/PostBrokerSettingsRequestRemoveIntegration'
            schema:
              additionalProperties: false
              properties:
                data:
                  $ref: '#/components/schemas/BrokerSettings'
              required:
              - data
              type: object
        required: true
      responses:
        '200':
          content:
            application/vnd.api+json:
              examples:
                WithIntegrations:
                  $ref: '#/components/examples/PostBrokerSettingsResponse'
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/BrokerSettings'
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    $ref: '#/components/schemas/PaginatedLinks'
          description: Successfully updated Broker settings
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: Update opensource broker settings of ecosystem for organization
      tags:
      - OpenSourceSettings
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - '2024-10-15'
      x-snyk-api-resource: opensourceSettings
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-10-15'
      x-stability-level: stable
components:
  examples:
    PostBrokerSettingsRequestAddIntegration:
      summary: Add an integration
      value:
        data:
          integrations:
          - integration_type: artifactory
            urls:
            - https://artifactory.internal-domain.com/artifactory/api/nuget/v3/team-nuget/index.json
    GetBrokerSettingsResponseWithIntegrations:
      summary: Broker settings with some integrations configured
      value:
        data:
          integrations:
          - created_at: '2026-04-15T10:00:00.000Z'
            id: 019d7722-72c3-7ae4-bb4e-40deea1820c0
            integration_type: artifactory
            urls:
            - https://artifactory.internal-domain.com/artifactory/api/nuget/v3/nuget-group/index.json
          - created_at: '2026-04-16T10:00:00.000Z'
            id: 019d7722-90bd-7bc0-9666-775eee165cf0
            integration_type: nexus-private-repo
            urls:
            - https://nexus.internal-domain.com/repository/nuget-hosted/index.json
            - https://nexus.internal-domain.com/repository/nuget-proxy/index.json
        jsonapi:
          version: '1.0'
        links:
          self: /orgs/db2557c3-ecb8-4d45-8e1e-894ae89a92a6/settings/opensource/Dotnet/broker?version=2024-10-15
    PostBrokerSettingsRequestEditIntegrations:
      summary: Edit multiple integrations at once
      value:
        data:
          integrations:
          - integration_type: artifactory
            urls:
            - https://artifactory.internal-domain.com/artifactory/api/nuget/v3/sandbox-nuget/index.json
            - https://artifactory.internal-domain.com/artifactory/api/nuget/v3/production-nuget/index.json
          - integration_type: nexus-private-repo
            urls: []
    GetBrokerSettingsResponseEmpty:
      summary: No integrations configured
      value:
        data:
          integrations: []
        jsonapi:
          version: '1.0'
        links:
          self: /orgs/82b3efbb-4b32-4f96-8005-9444eceacec8/settings/opensource/Dotnet/broker?version=2024-10-15
    PostBrokerSettingsRequestRemoveIntegration:
      summary: Remove an integration by setting empty urls
      value:
        data:
          integrations:
          - integration_type: nexus-private-repo
            urls: []
    PostBrokerSettingsResponse:
      summary: Response after updating broker settings
      value:
        data:
          integrations:
          - created_at: '2024-01-15T10:00:00.000Z'
            id: 019d7722-d843-7b9f-a1dd-bd5c0bac373d
            integration_type: artifactory
            urls:
            - https://artifactory.internal-domain.com/artifactory/api/nuget/v3/team-nuget/index.json
        jsonapi:
          version: '1.0'
        links:
          self: /orgs/4f4fbf18-b2cd-4bf3-9b7e-323b8be249ea/settings/opensource/Dotnet/broker?version=2024-10-15
  headers:
    SunsetHeader:
      description: 'A header containing the date of when the underlying endpoint will be removed. This header is only present if the endpoint has been deprecated. For information purposes only. Returned as a date in the format: YYYY-MM-DD'
      example: '2021-08-02'
      schema:
        format: date
        type: string
    VersionRequestedResponseHeader:
      description: A header containing the version of the endpoint requested by the caller.
      example: '2026-03-25'
      schema:
        $ref: '#/components/schemas/QueryVersion'
    VersionServedResponseHeader:
      description: A header containing the version of the endpoint that was served by the API.
      example: '2026-03-25'
      schema:
        $ref: '#/components/schemas/ActualVersion'
    VersionStageResponseHeader:
      description: 'A header containing the version stage of the endpoint. This stage describes the guarantees snyk provides surrounding stability of the endpoint.

        '
      schema:
        enum:
        - wip
        - experimental
        - beta
        - ga
        - deprecated
        - sunset
        example: ga
        type: string
    RequestIdResponseHeader:
      description: 'A header containing a unique id used for tracking this request. If you are reporting an issue to Snyk it''s very helpful to provide this ID.

        '
      example: 4b58e274-ec62-4fab-917b-1d2c48d6bdef
      schema:
        format: uuid
        type: string
    LocationHeader:
      description: 'A header providing a URL for the location of a resource

        '
      example: https://example.com/resource/4
      schema:
        format: url
        type: string
    DeprecationHeader:
      description: 'A header containing the deprecation date of the underlying endpoint. For more information, please refer to the deprecation header RFC:

        https://tools.ietf.org/id/draft-dalal-deprecation-header-01.html

        '
      example: '2021-07-01T00:00:00Z'
      schema:
        format: date-time
        type: string
  schemas:
    BrokerIntegration:
      additionalProperties: false
      properties:
        created_at:
          description: When this integration was created
          format: date-time
          readOnly: true
          type: string
        id:
          description: The unique identifier for the ecosystem integration
          format: uuid
          readOnly: true
          type: string
        integration_type:
          description: The type of integration (e.g., 'artifactory', 'nexus-private-repo')
          enum:
          - artifactory
          - nexus-private-repo
          example: artifactory
          type: string
        urls:
          description: Array of URLs associated with this integration. Set this field to undefined, an empty array, or omit it to delete the integration.
          example:
          - https://my-custom-artifactory.internal/artifactory/api/nuget/v3/my-nuget/index.json
          - https://my-custom-artifactory.internal/artifactory/api/nuget/v3/my-other-nuget/index.json
          - https://my-custom-artifactory.internal/artifactory/api/go/my-go-modules
          items:
            format: uri
            maxLength: 2048
            type: string
          type: array
      required:
      - integration_type
      type: object
    ActualVersion:
      description: Resolved API version
      example: '2026-03-25'
      pattern: ^((([0-9]{4})-([0-1][0-9]))-((3[01])|(0[1-9])|([12][0-9]))(~(wip|work-in-progress|experimental|beta))?)$
      type: string
    JsonApi:
      additionalProperties: false
      example:
        version: '1.0'
      properties:
        version:
          description: Version of the JSON API specification this server supports.
          example: '1.0'
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)$
          type: string
      required:
      - version
      type: object
    QueryVersion:
      description: Requested API version
      example: '2026-03-25'
      pattern: ^(wip|work-in-progress|experimental|beta|((([0-9]{4})-([0-1][0-9]))-((3[01])|(0[1-9])|([12][0-9]))(~(wip|work-in-progress|experimental|beta))?))$
      type: string
    ErrorDocument:
      additionalProperties: false
      example:
        errors:
        - detail: Permission denied for this resource
          status: '403'
        jsonapi:
          version: '1.0'
      properties:
        errors:
          example:
          - detail: Permission denied for this resource
            status: '403'
          items:
            additionalProperties: false
            example:
              detail: Not Found
              status: '404'
            properties:
              code:
                description: An application-specific error code, expressed as a string value.
                example: entity-not-found
                type: string
              detail:
                description: A human-readable explanation specific to this occurrence of the problem.
                example: 'The request was missing these required fields: ...'
                type: string
              id:
                description: A unique identifier for this particular occurrence of the problem.
                example: f16c31b5-6129-4571-add8-d589da9be524
                format: uuid
                type: string
              links:
                additionalProperties: false
                description: A link that leads to further details about this particular occurrance of the problem.
                example:
                  about: https://example.com/about_this_error
                properties:
                  about:
                    example: https://example.com/api/resource
                    oneOf:
                    - description: A string containing the link’s URL.
                      example: https://example.com/api/resource
                      type: string
                    - additionalProperties: false
                      example:
                        href: https://example.com/api/resource
                      properties:
                        href:
                          description: A string containing the link’s URL.
                          example: https://example.com/api/resource
                          type: string
                        meta:
                          additionalProperties: true
                          description: Free-form object that may contain non-standard information.
                          example:
                            key1: value1
                            key2:
                              sub_key: sub_value
                            key3:
                            - array_value1
                            - array_value2
                          type: object
                      required:
                      - href
                      type: object
                type: object
              meta:
                additionalProperties: true
                example:
                  key: value
                type: object
              source:
                additionalProperties: false
                example:
                  pointer: /data/attributes
                properties:
                  parameter:
                    description: A string indicating which URI query parameter caused the error.
                    example: param1
                    type: string
                  pointer:
                    description: A JSON Pointer [RFC6901] to the associated entity in the request document.
                    example: /data/attributes
                    type: string
                type: object
              status:
                description: The HTTP status code applicable to this problem, expressed as a string value.
                example: '400'
                pattern: ^[45]\d\d$
                type: string
              title:
                description: A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
                example: Bad request
                type: string
            required:
            - status
            - detail
            type: object
          minItems: 1
          type: array
        jsonapi:
          additionalProperties: false
          example:
            version: '1.0'
          properties:
            version:
              description: Version of the JSON API specification this server supports.
              example: '1.0'
              pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)$
              type: string
          required:
          - version
          type: object
      required:
      - jsonapi
      - errors
      type: object
    SelfLink:
      additionalProperties: false
      example:
        self: https://example.com/api/this_resource
      properties:
        self:
          $ref: '#/components/schemas/LinkProperty'
      type: object
    BrokerSettings:
      additionalProperties: false
      properties:
        integrations:
          items:
            $ref: '#/components/schemas/BrokerIntegration'
          type: array
      required:
      - integrations
      type: object
    Links:
      additionalProperties: false
      properties:
        first:
          $ref: '#/components/schemas/LinkProperty'
        last:
          $ref: '#/components/schemas/LinkProperty'
        next:
          $ref: '#/components/schemas/LinkProperty'
        prev:
          $ref: '#/components/schemas/LinkProperty'
        related:
          $ref: '#/components/schemas/LinkProperty'
        self:
          $ref: '#/components/schemas/LinkProperty'
      type: object
    PaginatedLinks:
      additionalProperties: false
      example:
        first: https://example.com/api/resource?ending_before=v1.eyJpZCI6IjExIn0K
        last: https://example.com/api/resource?starting_after=v1.eyJpZCI6IjMwIn0K
        next: https://example.com/api/resource?starting_after=v1.eyJpZCI6IjEwIn0K
      properties:
        first:
          $ref: '#/components/schemas/LinkProperty'
        last:
          $ref: '#/components/schemas/LinkProperty'
        next:
          $ref: '#/components/schemas/LinkProperty'
        prev:
          $ref: '#/components/schemas/LinkProperty'
        self:
          $ref: '#/components/schemas/LinkProperty'
      type: object
    LinkProperty:
      example: https://example.com/api/resource
      oneOf:
      - description: A string containing the link’s URL.
        example: https://example.com/api/resource
        type: string
      - additionalProperties: false
        example:
          href: https://example.com/api/resource
        properties:
          href:
            description: A string containing the link’s URL.
            example: https://example.com/api/resource
            type: string
          meta:
            additionalProperties: true
            description: Free-form object that may contain non-standard information.
            example:
              key1: value1
              key2:
                sub_key: sub_value
              key3:
              - array_value1
              - array_value2
            type: object
        required:
        - href
        type: object
  responses:
    '400':
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorDocument'
      description: 'Bad Request: A parameter provided as a part of the request was invalid.'
      headers:
        deprecation:
          $ref: '#/components/headers/DeprecationHeader'
        snyk-request-id:
          $ref: '#/components/headers/RequestIdResponseHeader'
        snyk-version-lifecycle-stage:
          $ref: '#/components/headers/VersionStageResponseHeader'
        snyk-version-requested:
          $ref: '#/components/headers/VersionRequestedResponseHeader'
        snyk-version-served:
          $ref: '#/components/headers/VersionServedResponseHeader'
        sunset:
          $ref: '#/components/headers/SunsetHeader'
    '500':
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorDocument'
      description: 'Internal Server Error: An error was encountered while attempting to process the request.'
      headers:
        deprecation:
          $ref: '#/components/headers/DeprecationHeader'
        snyk-request-id:
          $ref: '#/components/headers/RequestIdResponseHeader'
        snyk-version-lifecycle-stage:
          $ref: '#/components/headers/VersionStageResponseHeader'
        snyk-version-requested:
          $ref: '#/components/headers/VersionRequestedResponseHeader'
        snyk-version-served:
          $ref: '#/components/headers/VersionServedResponseHeader'
        sunset:
          $ref: '#/components/headers/SunsetHeader'
    '403':
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorDocument'
      description: 'Forbidden: the request requires an authentication token with more or different permissions.'
      headers:
        deprecation:
          $ref: '#/components/headers/DeprecationHeader'
        snyk-request-id:
          $ref: '#/components/headers/RequestIdResponseHeader'
        snyk-version-lifecycle-stage:
          $ref: '#/components/headers/VersionStageResponseHeader'
        snyk-version-requested:
          $ref: '#/components/headers/VersionRequestedResponseHeader'
        snyk-version-served:
          $ref: '#/components/headers/VersionServedResponseHeader'
        sunset:
          $ref: '#/components/headers/SunsetHeader'
    '404':
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorDocument'
      description: 'Not Found: The resource being operated on could not be found.'
      headers:
        deprecation:
          $ref: '#/components/headers/DeprecationHeader'
        snyk-request-id:
          $ref: '#/components/headers/RequestIdResponseHeader'
        snyk-version-lifecycle-stage:
          $ref: '#/components/headers/VersionStageResponseHeader'
        snyk-version-requested:
          $ref: '#/components/headers/VersionRequestedResponseHeader'
        snyk-version-served:
          $ref: '#/components/headers/VersionServedResponseHeader'
        sunset:
          $ref: '#/components/headers/SunsetHeader'
    '401':
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorDocument'
      description: 'Unauthorized: the request requires an authentication token.'
      headers:
        deprecation:
          $ref: '#/components/headers/DeprecationHeader'
        snyk-request-id:
          $ref: '#/components/headers/RequestIdResponseHeader'
        snyk-version-lifecycle-stage:
          $ref: '#/components/headers/VersionStageResponseHeader'
        snyk-version-requested:
          $ref: '#/components/headers/VersionRequestedResponseHeader'
        snyk-version-served:
          $ref: '#/components/headers/VersionServedResponseHeader'
        sunset:
          $ref: '#/components/headers/SunsetHeader'
  parameters:
    Version:
      description: The requested version of the endpoint to process the request
      example: '2026-03-25'
      in: query
      name: version
      required: true
      schema:
        $ref: '#/components/schemas/QueryVersion'
  requestBodies:
    EmptyRequestBody:
      content:
        application/vnd.api+json:
          schema:
            additionalProperties: false
            properties:
              data:
                additionalProperties: false
                type: object
            type: object
  securitySchemes:
    APIToken:
      description: API key value must be prefixed with \"Token \".
      in: header
      name: Authorization
      type: apiKey
    BearerAuth:
      scheme: bearer
      type: http
x-snyk-api-version: '2024-10-15'
