openapi: 3.0.3
info:
  title: Snyk AccessRequests Orgs API
  version: REST
servers:
- description: Snyk REST API
  url: https://api.snyk.io/rest
security:
- APIToken: []
- BearerAuth: []
tags:
- name: Orgs
paths:
  /groups/{group_id}/orgs:
    get:
      description: 'Get a paginated list of all the organizations belonging to the group.

        By default, this endpoint returns the organizations in alphabetical order of their name.


        #### Required permissions


        - `View Groups (group.read)`


        - `View Organizations (group.org.list)`'
      operationId: listOrgsInGroup
      parameters:
      - $ref: '#/components/parameters/Version'
      - $ref: '#/components/parameters/StartingAfter'
      - $ref: '#/components/parameters/EndingBefore'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/PathGroupId'
      - $ref: '#/components/parameters/QueryNameFilter'
      - $ref: '#/components/parameters/QuerySlugFilter'
      - $ref: '#/components/parameters/QueryExpand'
      responses:
        '200':
          content:
            application/vnd.api+json:
              schema:
                additionalProperties: false
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/Org'
                    type: array
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    $ref: '#/components/schemas/PaginatedLinks'
                  meta:
                    $ref: '#/components/schemas/ListOrgsInGroupMeta'
                required:
                - jsonapi
                - data
                - links
                type: object
          description: A list of organizations in the group.
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: List all organizations in group
      tags:
      - Orgs
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - 2023-10-24~experimental
      - 2023-12-14~beta
      - '2024-02-28'
      x-snyk-api-resource: orgs
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-02-28'
      x-stability-level: stable
  /orgs:
    get:
      description: Get a paginated list of organizations you have access to.
      operationId: listOrgs
      parameters:
      - $ref: '#/components/parameters/Version'
      - $ref: '#/components/parameters/StartingAfter'
      - $ref: '#/components/parameters/EndingBefore'
      - $ref: '#/components/parameters/Limit'
      - description: If set, only return organizations within the specified group
        in: query
        name: group_id
        schema:
          format: uuid
          type: string
      - description: If true, only return organizations that are not part of a group.
        in: query
        name: is_personal
        schema:
          type: boolean
      - description: Only return orgs whose slug exactly matches this value.
        in: query
        name: slug
        schema:
          maxLength: 100
          pattern: ^[\w.-]+$
          type: string
      - description: Only return orgs whose name contains this value.
        in: query
        name: name
        schema:
          maxLength: 100
          type: string
      - description: Expand the specified related resources in the response to include their attributes.
        in: query
        name: expand
        schema:
          items:
            enum:
            - member_role
            type: string
          type: array
      responses:
        '200':
          content:
            application/vnd.api+json:
              schema:
                additionalProperties: false
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/OrgWithRelationships'
                    type: array
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    $ref: '#/components/schemas/PaginatedLinks'
                required:
                - jsonapi
                - data
                - links
                type: object
          description: A list of organizations you have access to.
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: List accessible organizations
      tags:
      - Orgs
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - 2022-04-06~experimental
      - 2022-12-15~beta
      - '2023-05-29'
      - '2024-02-28'
      x-snyk-api-resource: orgs
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-02-28'
      x-stability-level: stable
  /orgs/{org_id}:
    get:
      description: 'Get the full details of an organization.


        #### Required permissions


        - `View Organization (org.read)`'
      operationId: getOrg
      parameters:
      - $ref: '#/components/parameters/Version'
      - description: Unique identifier for org
        in: path
        name: org_id
        required: true
        schema:
          example: b667f176-df52-4b0a-9954-117af6b05ab7
          format: uuid
          type: string
      - description: Expand the specified related resources in the response to include their attributes.
        in: query
        name: expand
        schema:
          items:
            enum:
            - tenant
            type: string
          type: array
      responses:
        '200':
          content:
            application/vnd.api+json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/Org20230529'
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    $ref: '#/components/schemas/SelfLink'
                type: object
          description: Returns an instance of an organization
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '409':
          $ref: '#/components/responses/409'
        '500':
          $ref: '#/components/responses/500'
      summary: Get organization
      tags:
      - Orgs
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - 2022-04-06~experimental
      - 2022-12-15~beta
      - '2023-05-29'
      x-snyk-api-resource: orgs
      x-snyk-api-stability: ga
      x-snyk-api-version: '2023-05-29'
      x-stability-level: stable
    patch:
      description: 'Update the details of an organization


        #### Required permissions


        - `Edit Organization (org.edit)`'
      operationId: updateOrg
      parameters:
      - $ref: '#/components/parameters/Version'
      - $ref: '#/components/parameters/PathOrgId'
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              properties:
                data:
                  additionalProperties: false
                  properties:
                    attributes:
                      $ref: '#/components/schemas/OrgUpdateAttributes'
                    id:
                      description: The ID of the resource.
                      format: uuid
                      type: string
                    type:
                      description: The type of the resource.
                      enum:
                      - org
                      example: org
                      type: string
                  required:
                  - id
                  - type
                  - attributes
                  type: object
              required:
              - data
              type: object
      responses:
        '200':
          content:
            application/vnd.api+json:
              schema:
                properties:
                  data:
                    additionalProperties: false
                    description: org resource object
                    properties:
                      attributes:
                        $ref: '#/components/schemas/OrgAttributes'
                      id:
                        example: d5b640e5-d88c-4c17-9bf0-93597b7a1ce2
                        format: uuid
                        type: string
                      relationships:
                        $ref: '#/components/schemas/OrgRelationships'
                      type:
                        enum:
                        - org
                        example: org
                        type: string
                    required:
                    - id
                    - type
                    type: object
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    $ref: '#/components/schemas/SelfLink'
                type: object
          description: Instance of org is updated
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '204':
          $ref: '#/components/responses/204'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '409':
          $ref: '#/components/responses/409'
        '500':
          $ref: '#/components/responses/500'
      summary: Update organization
      tags:
      - Orgs
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - 2022-04-06~experimental
      - 2022-12-15~beta
      - '2023-05-29'
      - '2024-02-28'
      x-snyk-api-resource: orgs
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-02-28'
      x-stability-level: stable
  /orgs/{org_id}/memberships:
    get:
      description: 'Returns all memberships of the org


        #### Required permissions


        - `View Organization Memberships (org.membership.read)`'
      operationId: listOrgMemberships
      parameters:
      - description: The ID of the org
        in: path
        name: org_id
        required: true
        schema:
          format: uuid
          type: string
      - $ref: '#/components/parameters/StartingAfter'
      - $ref: '#/components/parameters/EndingBefore'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Version'
      - description: Which column to sort by.
        in: query
        name: sort_by
        schema:
          enum:
          - username
          - user_display_name
          - email
          - login_method
          - role
          type: string
      - description: Order in which results are returned.
        example: ASC
        in: query
        name: sort_order
        schema:
          default: ASC
          enum:
          - ASC
          - DESC
          type: string
      - $ref: '#/components/parameters/EmailFilter'
      - $ref: '#/components/parameters/UserIdFilter'
      - $ref: '#/components/parameters/UsernameFilter'
      - $ref: '#/components/parameters/RoleFilter'
      responses:
        '200':
          content:
            application/vnd.api+json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/OrgMembershipResponseData'
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    $ref: '#/components/schemas/Links'
                required:
                - jsonapi
                - data
                - links
                type: object
          description: List of org memberships is returned
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: Get all memberships of the org
      tags:
      - Orgs
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - 2024-05-09~experimental
      - '2024-08-25'
      x-snyk-api-resource: orgs
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-08-25'
      x-stability-level: stable
    post:
      description: 'Create a org membership for a user with role


        #### Required permissions


        - `Add Organization Memberships (org.membership.add)`'
      operationId: createOrgMembership
      parameters:
      - description: The ID of the org
        in: path
        name: org_id
        required: true
        schema:
          format: uuid
          type: string
      - $ref: '#/components/parameters/Version'
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateOrgMembershipRequestBody20240825'
      responses:
        '201':
          content:
            application/vnd.api+json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/OrgMembership'
                  jsonapi:
                    $ref: '#/components/schemas/JsonApi'
                  links:
                    $ref: '#/components/schemas/Links'
                type: object
          description: Membership for the user is created on the org
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            location:
              $ref: '#/components/headers/LocationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '409':
          $ref: '#/components/responses/409'
        '500':
          $ref: '#/components/responses/500'
      summary: Create a org membership for a user with role
      tags:
      - Orgs
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - 2024-05-09~experimental
      - '2024-08-25'
      x-snyk-api-resource: orgs
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-08-25'
      x-stability-level: stable
  /orgs/{org_id}/memberships/{membership_id}:
    delete:
      description: 'Remove a user''s membership of the group.


        #### Required permissions


        - `Delete Organization Memberships (org.membership.delete)`'
      operationId: deleteOrgMembership
      parameters:
      - description: The id of the org
        in: path
        name: org_id
        required: true
        schema:
          format: uuid
          type: string
      - $ref: '#/components/parameters/OrgMembershipId'
      - $ref: '#/components/parameters/Version'
      responses:
        '204':
          description: Org membership for the user was successfully deleted.
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      summary: Remove user's org membership
      tags:
      - Orgs
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - 2024-06-06~experimental
      - '2024-08-25'
      x-snyk-api-resource: org_memberships
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-08-25'
      x-stability-level: stable
    patch:
      description: 'Update a org membership for a user with role


        #### Required permissions


        - `Edit Organization Memberships (org.membership.edit)`'
      operationId: updateOrgMembership
      parameters:
      - description: The id of the org
        in: path
        name: org_id
        required: true
        schema:
          format: uuid
          type: string
      - $ref: '#/components/parameters/OrgMembershipId'
      - $ref: '#/components/parameters/Version'
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              properties:
                data:
                  $ref: '#/components/schemas/UpdateOrgMembershipRequestBody20240825'
              required:
              - data
              type: object
      responses:
        '204':
          description: The Membership is updated
          headers:
            deprecation:
              $ref: '#/components/headers/DeprecationHeader'
            snyk-request-id:
              $ref: '#/components/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/headers/VersionStageResponseHeader'
            snyk-version-requested:
              $ref: '#/components/headers/VersionRequestedResponseHeader'
            snyk-version-served:
              $ref: '#/components/headers/VersionServedResponseHeader'
            sunset:
              $ref: '#/components/headers/SunsetHeader'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '409':
          $ref: '#/components/responses/409'
        '500':
          $ref: '#/components/responses/500'
      summary: Update a org membership for a user with role
      tags:
      - Orgs
      x-snyk-api-lifecycle: released
      x-snyk-api-releases:
      - 2024-06-06~experimental
      - '2024-08-25'
      x-snyk-api-resource: org_memberships
      x-snyk-api-stability: ga
      x-snyk-api-version: '2024-08-25'
      x-stability-level: stable
components:
  parameters:
    EndingBefore:
      description: Return the page of results immediately before this cursor
      example: v1.eyJpZCI6IjExMDAifQo=
      in: query
      name: ending_before
      schema:
        type: string
    StartingAfter:
      description: Return the page of results immediately after this cursor
      example: v1.eyJpZCI6IjEwMDAifQo=
      in: query
      name: starting_after
      schema:
        type: string
    RoleFilter:
      description: Filter the response for results only with the specified role.
      in: query
      name: role_name
      schema:
        type: string
    QuerySlugFilter:
      description: Only return organizations whose slug exactly matches this value. Case sensitive.
      in: query
      name: slug
      schema:
        type: string
    Version:
      description: The requested version of the endpoint to process the request
      example: '2026-03-25'
      in: query
      name: version
      required: true
      schema:
        $ref: '#/components/schemas/QueryVersion'
    Limit:
      description: Number of results to return per page
      example: 10
      in: query
      name: limit
      schema:
        default: 10
        format: int32
        maximum: 100
        minimum: 10
        multipleOf: 10
        type: integer
    EmailFilter:
      description: Filter the response by Users that match the provided email
      in: query
      name: email
      schema:
        type: string
    PathGroupId:
      description: Unique identifier for group
      in: path
      name: group_id
      required: true
      schema:
        example: b667f176-df52-4b0a-9954-117af6b05ab7
        format: uuid
        type: string
    PathOrgId:
      description: Unique identifier for org
      in: path
      name: org_id
      required: true
      schema:
        example: b667f176-df52-4b0a-9954-117af6b05ab7
        format: uuid
        type: string
    UsernameFilter:
      description: Filter the response by Users that match the provided username
      in: query
      name: username
      schema:
        type: string
    QueryNameFilter:
      description: Only return organizations whose name contains this value. Case insensitive.
      in: query
      name: name
      schema:
        type: string
    OrgMembershipId:
      description: The id of the org membership
      in: path
      name: membership_id
      required: true
      schema:
        format: uuid
        type: string
    QueryExpand:
      description: Expand the response with additional fields. When set to `count`, the response will include a `meta` object containing a `total_count` field with the total number of organizations in the group, ignoring any filters applied to the original query.
      in: query
      name: expand
      schema:
        enum:
        - count
        example: count
        type: string
    UserIdFilter:
      description: Filter the response by Users that match the provided user ID
      in: query
      name: user_id
      schema:
        type: string
  schemas:
    Org:
      additionalProperties: false
      properties:
        attributes:
          $ref: '#/components/schemas/OrgAttributes'
        id:
          description: The Snyk ID of the organization.
          example: 59d6d97e-3106-4ebb-b608-352fad9c5b34
          format: uuid
          type: string
        type:
          $ref: '#/components/schemas/Types'
      required:
      - type
      - id
      - attributes
      type: object
    OrgMembershipOrgData:
      properties:
        data:
          additionalProperties: false
          properties:
            attributes:
              properties:
                name:
                  description: The name of the organization
                  example: Example org
                  type: string
              required:
              - name
              type: object
            id:
              example: 331ede0a-de94-456f-b788-166caeca58bf
              format: uuid
              type: string
            type:
              example: org
              type: string
          required:
          - id
          - attributes
          type: object
      type: object
    ActualVersion:
      description: Resolved API version
      example: '2026-03-25'
      pattern: ^((([0-9]{4})-([0-1][0-9]))-((3[01])|(0[1-9])|([12][0-9]))(~(wip|work-in-progress|experimental|beta))?)$
      type: string
    OrgMembershipAttributes:
      additionalProperties: false
      properties:
        created_at:
          description: The time when this Org membership was created
          example: '2022-03-16T00:00:00Z'
          format: date-time
          type: string
      required:
      - created_at
      type: object
    JsonApi:
      additionalProperties: false
      example:
        version: '1.0'
      properties:
        version:
          description: Version of the JSON API specification this server supports.
          example: '1.0'
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)$
          type: string
      required:
      - version
      type: object
    OrgRelationships:
      additionalProperties: false
      properties:
        member_role:
          $ref: '#/components/schemas/MemberRoleRelationship'
      type: object
    QueryVersion:
      description: Requested API version
      example: '2026-03-25'
      pattern: ^(wip|work-in-progress|experimental|beta|((([0-9]{4})-([0-1][0-9]))-((3[01])|(0[1-9])|([12][0-9]))(~(wip|work-in-progress|experimental|beta))?))$
      type: string
    OrgMembershipUserData:
      properties:
        data:
          additionalProperties: false
          properties:
            attributes:
              properties:
                email:
                  description: The email of the user
                  example: user@test.com
                  type: string
                login_method:
                  description: The login method of the user
                  type: string
                name:
                  description: The name of the user
                  example: User2
                  type: string
                username:
                  description: The username of the user
                  example: User name 2
                  type: string
              required:
              - name
              - username
              - email
              type: object
            id:
              example: 331ede0a-de94-456f-b788-166caeca58bf
              format: uuid
              type: string
            type:
              example: user
              type: string
          required:
          - id
          - attributes
          type: object
      type: object
    OrgUpdateAttributes:
      additionalProperties: false
      properties:
        name:
          description: The display name of the organization.
          example: My Org
          maxLength: 60
          minLength: 1
          type: string
      required:
      - name
      type: object
    OrgMembershipRoleData:
      properties:
        data:
          additionalProperties: false
          properties:
            attributes:
              properties:
                name:
                  description: The name of the role
                  example: Admin role
                  type: string
              required:
              - name
              type: object
            id:
              example: 331ede0a-de94-456f-b788-166caeca58bf
              format: uuid
              type: string
            type:
              example: org_role
              type: string
          required:
          - id
          - attributes
          type: object
      type: object
    UpdateOrgMembershipRequestBody20240825:
      additionalProperties: false
      properties:
        attributes:
          type: object
        id:
          description: The Snyk ID of the organization.
          example: f60ff965-6889-4db2-8c86-0285d62f35ab
          format: uuid
          type: string
        relationships:
          additionalProperties: false
          properties:
            role:
              properties:
                data:
                  additionalProperties: false
                  properties:
                    id:
                      description: The Snyk ID of the Org Role.
                      example: f60ff965-6889-4db2-8c86-0285d62f35ab
                      format: uuid
                      type: string
                    type:
                      description: The type of the resource. Always 'org_role'.
                      example: org_role
                      type: string
                  required:
                  - type
                  - id
                  type: object
              type: object
          required:
          - role
          type: object
        type:
          description: The type of the resource. Always 'org_membership'.
          example: org_membership
          type: string
      required:
      - type
      - id
      - relationships
      type: object
    OrgAttributes20230529:
      additionalProperties: false
      properties:
        created_at:
          description: The time the organization was created.
          example: '2022-03-16T00:00:00Z'
          format: date-time
          type: string
        group_id:
          description: The Snyk ID of the group to which the organization belongs.
          example: 59d6d97e-3106-4ebb-b608-352fad9c5b34
          format: uuid
          type: string
        is_personal:
          description: Whether the organization is independent (that is, not part of a group).
          example: true
          type: boolean
        name:
          description: The display name of the organization.
          example: My Org
          type: string
        slug:
          description: The canonical (unique and URL-friendly) name of the organization.
          example: my-org
          type: string
        updated_at:
          description: The time the organization was last modified.
          example: '2022-03-16T00:00:00Z'
          format: date-time
          type: string
      required:
      - name
      - slug
      - is_personal
      type: object
    ErrorDocument:
      additionalProperties: false
      example:
        errors:
        - detail: Permission denied for this resource
          status: '403'
        jsonapi:
          version: '1.0'
      properties:
        errors:
          example:
          - detail: Permission denied for this resource
            status: '403'
          items:
            additionalProperties: false
            example:
              detail: Not Found
              status: '404'
            properties:
              code:
                description: An application-specific error code, expressed as a string value.
                example: entity-not-found
                type: string
              detail:
                description: A human-readable explanation specific to this occurrence of the problem.
                example: 'The request was missing these required fields: ...'
                type: string
              id:
                description: A unique identifier for this particular occurrence of the problem.
                example: f16c31b5-6129-4571-add8-d589da9be524
                format: uuid
                type: string
              links:
                additionalProperties: false
                description: A link that leads to further details about this particular occurrance of the problem.
                example:
                  about: https://example.com/about_this_error
                properties:
                  about:
                    example: https://example.com/api/resource
                    oneOf:
                    - description: A string containing the link’s URL.
                      example: https://example.com/api/resource
                      type: string
                    - additionalProperties: false
                      example:
                        href: https://example.com/api/resource
                      properties:
                        href:
                          description: A string containing the link’s URL.
                          example: https://example.com/api/resource
                          type: string
                        meta:
                          additionalProperties: true
                          description: Free-form object that may contain non-standard information.
                          example:
                            key1: value1
                            key2:
                              sub_key: sub_value
                            key3:
                            - array_value1
                            - array_value2
                          type: object
                      required:
                      - href
                      type: object
                type: object
              meta:
                additionalProperties: true
                example:
                  key: value
                type: object
              source:
                additionalProperties: false
                example:
                  pointer: /data/attributes
                properties:
                  parameter:
                    description: A string indicating which URI query parameter caused the error.
                    example: param1
                    type: string
                  pointer:
                    description: A JSON Pointer [RFC6901] to the associated entity in the request document.
                    example: /data/attributes
                    type: string
                type: object
              status:
                description: The HTTP status code applicable to this problem, expressed as a string value.
                example: '400'
                pattern: ^[45]\d\d$
                type: string
              title:
                description: A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
                example: Bad request
                type: string
            required:
            - status
            - detail
            type: object
          minItems: 1
          type: array
        jsonapi:
          additionalProperties: false
          example:
            version: '1.0'
          properties:
            version:
              description: Version of the JSON API specification this server supports.
              example: '1.0'
              pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)$
              type: string
          required:
          - version
          type: object
      required:
      - jsonapi
      - errors
      type: object
    OrgRoleAttributes:
      properties:
        name:
          description: The display name of the organization role.
          example: Collaborator
          type: string
      type: object
    OrgMembershipRelationships:
      additionalProperties: false
      properties:
        org:
          $ref: '#/components/schemas/OrgMembershipOrgData'
        role:
          $ref: '#/components/schemas/OrgMembershipRoleData'
        user:
          $ref: '#/components/schemas/OrgMembershipUserData'
      required:
      - role
      - org
      - user
      type: object
    SelfLink:
      additionalProperties: false
      example:
        self: https://example.com/api/this_resource
      properties:
        self:
          $ref: '#/components/schemas/LinkProperty'
      type: object
    OrgWithRelationships:
      additionalProperties: false
      properties:
        attributes:
          $ref: '#/components/schemas/OrgAttributes'
        id:
          description: The Snyk ID of the organization.
          example: 59d6d97e-3106-4ebb-b608-352fad9c5b34
          format: uuid
          type: string
        relationships:
          $ref: '#/components/schemas/OrgRelationships'
        type:
          $ref: '#/components/schemas/Types'
      required:
      - type
      - id
      - attributes
      type: object
    MemberRoleRelationship:
      additionalProperties: false
      nullable: true
      properties:
        data:
          additionalProperties: false
          properties:
            attributes:
              $ref: '#/components/schemas/OrgRoleAttributes'
            id:
              description: The Snyk ID of the organization role.
              example: f60ff965-6889-4db2-8c86-0285d62f35ab
              format: uuid
              type: string
            type:
              $ref: '#/components/schemas/Types'
          required:
          - type
          - id
          type: object
      required:
      - data
      type: object
    OrgMembership:
      additionalProperties: false
      properties:
        attributes:
          properties:
            created_at:
              description: The date that the org membership was created on
              example: '2021-05-29T09:50:54.014Z'
              format: date-time
          type: object
        id:
          example: 331ede0a-de94-456f-b788-166caeca58bf
          format: uuid
          type: string
        relationships:
          $ref: '#/components/schemas/OrgMembershipRelationships'
        type:
          description: Content type.
          example: org_membership
          type: string
      required:
      - type
      - id
      - attributes
      - relationships
      type: object
    Types:
      example: resource
      pattern: ^[a-z][a-z0-9]*(_[a-z][a-z0-9]*)*$
      type: string
    OrgAttributes:
      additionalProperties: false
      properties:
        access_requests_enabled:
          description: Whether the organization permits access requests from users who are not members of the organization.
          example: false
          type: boolean
        created_at:
          description: The time the organization was created.
          example: '2022-03-16T00:00:00Z'
          format: date-time
          type: string
        group_id:
          description: The Snyk ID of the group to which the organization belongs.
          example: 59d6d97e-3106-4ebb-b608-352fad9c5b34
          format: uuid
          type: string
        is_personal:
          description: Whether the organization is independent (that is, not part of a group).
          example: true
          type: boolean
        name:
          description: The display name of the organization.
          example: My Org
          type: string
        slug:
          description: The canonical (unique and URL-friendly) name of the organization.
          example: my-org
          type: string
        updated_at:
          description: The time the organization was last modified.
          example: '2022-03-16T00:00:00Z'
          format: date-time
          type: string
      required:
      - name
      - slug
      - is_personal
      type: object
    Links:
      additionalProperties: false
      properties:
        first:
          $ref: '#/components/schemas/LinkProperty'
        last:
          $ref: '#/components/schemas/LinkProperty'
        next:
          $ref: '#/components/schemas/LinkProperty'
        prev:
          $ref: '#/components/schemas/LinkProperty'
        related:
          $ref: '#/components/schemas/LinkProperty'
        self:
          $ref: '#/components/schemas/LinkProperty'
      type: object
    CreateOrgMembershipRequestBody20240825:
      properties:
        data:
          additionalProperties: false
          properties:
            relationships:
              additionalProperties: false
              properties:
                org:
                  additionalProperties: false
                  properties:
                    data:
                      properties:
                        id:
                          example: 8aab168e-fb3b-47c0-9d87-442715788b31
                          format: uuid
                          type: string
                        type:
                          description: Always "org"
                          enum:
                          - org
                          example: org
                          type: string
                      required:
                      - type
                      - id
                      type: object
                  required:
                  - data
                  type: object
                role:
                  additionalProperties: false
                  properties:
                    data:
                      properties:
                        id:
                          example: 331ede0a-de94-456f-b788-166caeca58bf
                          format: uuid
                          type: string
                        type:
                          description: Always "org_role"
                          enum:
                          - org_role
                          example: org_role
                          type: string
                      required:
                      - type
                      - id
                      type: object
                  required:
                  - data
                  type: object
                user:
                  additionalProperties: false
                  properties:
                    data:
                      properties:
                        id:
                          example: 677d5f47-a8bf-4090-ba52-680903e7c8b5
                          format: uuid
                          type: string
                        type:
                          description: Always "user"
                          enum:
                          - user
                          example: user
                          type: string
                      required:
                      - type
                      - id
                      type: object
                  required:
                  - data
                  type: object
              required:
              - role
              - user
              - org
              type: object
            type:
              description: type of membership according to its entity
              enum:
              - org_membership
              example: org_membership
              type: string
          required:
          - type
          - relationships
          type: object
      required:
      - data
      type: object
    PaginatedLinks:
      additionalProperties: false
      example:
        first: https://example.com/api/resource?ending_before=v1.eyJpZCI6IjExIn0K
        last: https://example.com/api/resource?starting_after=v1.eyJpZCI6IjMwIn0K
        next: https://example.com/api/resource?starting_after=v1.eyJpZCI6IjEwIn0K
      properties:
        first:
          $ref: '#/components/schemas/LinkProperty'
        last:
          $ref: '#/components/schemas/LinkProperty'
        next:
          $ref: '#/components/schemas/LinkProperty'
        prev:
          $ref: '#/components/schemas/LinkProperty'
        self:
          $ref: '#/components/schemas/LinkProperty'
      type: object
    Org20230529:
      additionalProperties: false
      properties:
        attributes:
          $ref: '#/components/schemas/OrgAttributes20230529'
        id:
          description: The Snyk ID of the organization.
          example: 59d6d97e-3106-4ebb-b608-352fad9c5b34
          format: uuid
          type: string
        relationships:
          properties:
            tenant:
              properties:
                data:
                  properties:
                    id:
                      example: 00000000-0000-0000-0000-000000000000
                      format: uuid
                      type: string
                    type:
                      description: The type of the resource for tenant operations
                      enum:
                      - tenant
                      type: string
                  type: object
              type: object
          type: object
        type:
          $ref: '#/components/schemas/Types'
      required:
      - type
      - id
      - attributes
      type: object
    ListOrgsInGroupMeta:
      additionalProperties: false
      description: Additional information about the list of organizations. Only populated when `expand=count` is supplied as a query parameter.
      properties:
        total_count:
          description: The total number of organizations in the group, ignoring any filters applied to the original query. Excludes soft-deleted organizations.
          example: 42
          format: int64
          minimum: 0
          type: integer
      required:
      - total_count
      type: object
    OrgMembershipResponseData:
      additionalProperties: false
      items:
        properties:
          attributes:
            $ref: '#/components/schemas/OrgMembershipAttributes'
          id:
            example: 331ede0a-de94-456f-b788-166caeca58bf
            format: uuid
            type: string
          relationships:
            $ref: '#/components/schemas/OrgMembershipRelationships'
          type:
            description: Content type
            example: org_memberships
            type: string
        type: object
      type: array
    LinkProperty:
      example: https://example.com/api/resource
      oneOf:
      - description: A string containing the link’s URL.
        example: https://example.com/api/resource
        type: string
      - additionalProperties: false
        example:
          href: https://example.com/api/resource
        properties:
          href:
            description: A string containing the link’s URL.
            example: https://example.com/api/resource
            type: string
          meta:
            additionalProperties: true
            description: Free-form object that may contain non-standard information.
            example:
              key1: value1
              key2:
                sub_key: sub_value
              key3:
              - array_value1
              - array_value2
            type: object
        required:
        - href
        type: object
  headers:
    SunsetHeader:
      description: 'A header containing the date of when the underlying endpoint will be removed. This header is only present if the endpoint has been deprecated. For information purposes only. Returned as a date in the format: YYYY-MM-DD'
      example: '2021-08-02'
      schema:
        format: date
        type: string
    VersionRequestedResponseHeader:
      description: A header containing the version of the endpoint requested by the caller.
      example: '2026-03-25'
      schema:
        $ref: '#/components/schemas/QueryVersion'
    VersionServedResponseHeader:
      description: A header containing the version of the endpoint that was served by the API.
      example: '2026-03-25'
      schema:
        $ref: '#/components/schemas/ActualVersion'
    VersionStageResponseHeader:
      description: 'A header containing the version stage of the endpoint. This stage describes the guarantees snyk provides surrounding stability of the endpoint.

        '
      schema:
        enum:
        - wip
        - experimental
        - beta
        - ga
        - deprecated
        - sunset
        example: ga
        type: string
    RequestIdResponseHeader:
      description: 'A header containing a unique id used for tracking this request. If you are reporting an issue to Snyk it''s very helpful to provide this ID.

        '
      example: 4b58e274-ec62-4fab-917b-1d2c48d6bdef
      schema:
        format: uuid
        type: string
    LocationHeader:
      description: 'A header providing a URL for the location of a resource

        '
      example: https://example.com/resource/4
      schema:
        format: url
        type: string
    DeprecationHeader:
      description: 'A header containing the deprecation date of the underlying endpoint. For more information, please refer to the deprecation header RFC:

        https://tools.ietf.org/id/draft-dalal-deprecation-header-01.html

        '
      example: '2021-07-01T00:00:00Z'
      schema:
        format: date-time
        type: string
  responses:
    '409':
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorDocument'
      description: 'Conflict: The requested operation conflicts with the current state of the resource in some way.'
      headers:
        deprecation:
          $ref: '#/components/headers/DeprecationHeader'
        snyk-request-id:
          $ref: '#/components/headers/RequestIdResponseHeader'
        snyk-version-lifecycle-stage:
          $ref: '#/components/headers/VersionStageResponseHeader'
        snyk-version-requested:
          $ref: '#/components/headers/VersionRequestedResponseHeader'
        snyk-version-served:
          $ref: '#/components/headers/VersionServedResponseHeader'
        sunset:
          $ref: '#/components/headers/SunsetHeader'
    '204':
      description: The operation completed successfully with no content
      headers:
        deprecation:
          $ref: '#/components/headers/DeprecationHeader'
        snyk-request-id:
          $ref: '#/components/headers/RequestIdResponseHeader'
        snyk-version-lifecycle-stage:
          $ref: '#/components/headers/VersionStageResponseHeader'
        snyk-version-requested:
          $ref: '#/components/headers/VersionRequestedResponseHeader'
        snyk-version-served:
          $ref: '#/components/headers/VersionServedResponseHeader'
        sunset:
          $ref: '#/components/headers/SunsetHeader'
    '500':
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorDocument'
      description: 'Internal Server Error: An error was encountered while attempting to process the request.'
      headers:
        deprecation:
          $ref: '#/components/headers/DeprecationHeader'
        snyk-request-id:
          $ref: '#/components/headers/RequestIdResponseHeader'
        snyk-version-lifecycle-stage:
          $ref: '#/components/headers/VersionStageResponseHeader'
        snyk-version-requested:
          $ref: '#/components/headers/VersionRequestedResponseHeader'
        snyk-version-served:
          $ref: '#/components/headers/VersionServedResponseHeader'
        sunset:
          $ref: '#/components/headers/SunsetHeader'
    '400':
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorDocument'
      description: 'Bad Request: A parameter provided as a part of the request was invalid.'
      headers:
        deprecation:
          $ref: '#/components/headers/DeprecationHeader'
        snyk-request-id:
          $ref: '#/components/headers/RequestIdResponseHeader'
        snyk-version-lifecycle-stage:
          $ref: '#/components/headers/VersionStageResponseHeader'
        snyk-version-requested:
          $ref: '#/components/headers/VersionRequestedResponseHeader'
        snyk-version-served:
          $ref: '#/components/headers/VersionServedResponseHeader'
        sunset:
          $ref: '#/components/headers/SunsetHeader'
    '403':
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorDocument'
      description: 'Forbidden: the request requires an authentication token with more or different permissions.'
      headers:
        deprecation:
          $ref: '#/components/headers/DeprecationHeader'
        snyk-request-id:
          $ref: '#/components/headers/RequestIdResponseHeader'
        snyk-version-lifecycle-stage:
          $ref: '#/components/headers/VersionStageResponseHeader'
        snyk-version-requested:
          $ref: '#/components/headers/VersionRequestedResponseHeader'
        snyk-version-served:
          $ref: '#/components/headers/VersionServedResponseHeader'
        sunset:
          $ref: '#/components/headers/SunsetHeader'
    '404':
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorDocument'
      description: 'Not Found: The resource being operated on could not be found.'
      headers:
        deprecation:
          $ref: '#/components/headers/DeprecationHeader'
        snyk-request-id:
          $ref: '#/components/headers/RequestIdResponseHeader'
        snyk-version-lifecycle-stage:
          $ref: '#/components/headers/VersionStageResponseHeader'
        snyk-version-requested:
          $ref: '#/components/headers/VersionRequestedResponseHeader'
        snyk-version-served:
          $ref: '#/components/headers/VersionServedResponseHeader'
        sunset:
          $ref: '#/components/headers/SunsetHeader'
    '401':
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorDocument'
      description: 'Unauthorized: the request requires an authentication token.'
      headers:
        deprecation:
          $ref: '#/components/headers/DeprecationHeader'
        snyk-request-id:
          $ref: '#/components/headers/RequestIdResponseHeader'
        snyk-version-lifecycle-stage:
          $ref: '#/components/headers/VersionStageResponseHeader'
        snyk-version-requested:
          $ref: '#/components/headers/VersionRequestedResponseHeader'
        snyk-version-served:
          $ref: '#/components/headers/VersionServedResponseHeader'
        sunset:
          $ref: '#/components/headers/SunsetHeader'
  securitySchemes:
    APIToken:
      description: API key value must be prefixed with \"Token \".
      in: header
      name: Authorization
      type: apiKey
    BearerAuth:
      scheme: bearer
      type: http
x-snyk-api-version: '2024-10-15'
